version: '3'

services:
  web:
    build: ./src
    volumes:
      - static:/app/app/static/
    networks:
      - web_nw
      - db_nw
    environment:
      FLASK_APP_CONFIG: "config.ProductionConfig"
    depends_on:
      - redis
      - db

  db:
    image: postgres:9.6.5
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db_nw

  redis:
    image: redis
    networks:
      - db_nw

  nginx:
    build: ./src/nginx
    volumes:
      - static:/app/app/static/
    networks:
      - web_nw
    depends_on:
      - web

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
   db:
   static:
