version: '3'

services:
  web:
    environment:
      DATABASE_URI: "postgresql://postgres:P@ssw0rd!@db/postgres"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      ADMIN_EMAIL: "admin@email.com"
      ADMIN_PASSWORD: "P@ssw0rd!"

  db:
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd!"

  nginx:
    ports:
      - "5000:80"
