"""addFKtoCatalogItems

Revision ID: 2c4b35d1e63c
Revises: 777293ea7b3f
Create Date: 2018-03-06 23:44:00.805494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4b35d1e63c'
down_revision = '777293ea7b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('catalog_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart_items', 'catalog_items', ['catalog_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'catalog_item_id')
    # ### end Alembic commands ###
