"""updateFK

Revision ID: 799791efddf5
Revises: 2c4b35d1e63c
Create Date: 2018-03-06 23:45:42.582886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799791efddf5'
down_revision = '2c4b35d1e63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('catalog_items_cart_item_id_fkey', 'catalog_items', type_='foreignkey')
    op.drop_column('catalog_items', 'cart_item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('cart_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('catalog_items_cart_item_id_fkey', 'catalog_items', 'cart_items', ['cart_item_id'], ['id'])
    # ### end Alembic commands ###
