"""initdb

Revision ID: d5ed6e7a04a3
Revises: 
Create Date: 2018-03-17 05:36:44.032991

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils as su
import sqlalchemy_searchable as ss


# revision identifiers, used by Alembic.
revision = 'd5ed6e7a04a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    op.create_table('carts',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('order_details',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=True),
                    sa.Column('price', sa.Numeric(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('index', sa.String(length=64), nullable=True),
                    sa.Column('default', sa.Boolean(), nullable=True),
                    sa.Column('permissions', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_roles_default'), 'roles',
                    ['default'], unique=False)
    op.create_table('catalog_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Unicode(length=50), nullable=True),
                    sa.Column('description', sa.String(
                        length=140), nullable=True),
                    sa.Column('image_url', sa.String(
                        length=140), nullable=True),
                    sa.Column('price', sa.Numeric(), nullable=True),
                    sa.Column('order_detail_id', sa.Integer(), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('search_vector',
                              su.TSVectorType(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['order_detail_id'], [
                                            'order_details.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_catalog_items_search_vector', 'catalog_items', [
                    'search_vector'], unique=False, postgresql_using='gin')
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order_total', sa.Numeric(), nullable=True),
                    sa.Column('order_placed', sa.DateTime(), nullable=True),
                    sa.Column('order_detail_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['order_detail_id'], [
                                            'order_details.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=64), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('password', sa.Binary(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'),
                    'users', ['username'], unique=True)
    op.create_table('cart_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=True),
                    sa.Column('cart_id', sa.String(), nullable=True),
                    sa.Column('catalog_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
                    sa.ForeignKeyConstraint(['catalog_item_id'], [
                        'catalog_items.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    ss.sync_trigger(conn, 'catalog_items', 'search_vector',
                    ['name', 'description'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('orders')
    op.drop_index('ix_catalog_items_search_vector', table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('order_details')
    op.drop_table('categories')
    op.drop_table('carts')
    # ### end Alembic commands ###
