version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      DATABASE_URI: "postgresql://postgres:P@ssw0rd!@db/postgres"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd!"

  redis:
    image: redis

