version: '3'

services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      DATABASE_URI: "postgresql://postgres:P@ssw0rd!@postgres/stationaryshop"
      REDIS_URI: "http://redis"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd!"

  redis:
    image: redis
